1

diff --git a/.github/workflows/2build_wr3000.yml b/.github/workflows/2build_wr3000.yml
--- a/.github/workflows/2build_wr3000.yml
+++ b/.github/workflows/2build_wr3000.yml
@@ -49,9 +49,13 @@ jobs:
         run: |
           sudo apt update
           sudo DEBIAN_FRONTEND=noninteractive apt install -y \
-            build-essential libncurses-dev libssl-dev zlib1g-dev libtool-bin \
-            autoconf automake pkg-config git curl wget ccache rsync gawk unzip time \
-            python3-setuptools quilt diffstat ed gettext subversion mold
+            build-essential ccache \
+            libncurses-dev libssl-dev zlib1g-dev \
+            libtool-bin autoconf automake \
+            python3-setuptools \
+            git curl wget rsync gawk unzip time \
+            quilt diffstat ed gettext subversion mold \
+            asciidoc xmlto sphinxsearch
 
       - name: Setup ccache
         run: |
@@ -128,8 +132,13 @@ jobs:
           export CCACHE_DIR="$CCACHE_DIR"
           export PATH="/usr/lib/ccache:$PATH"
           export LD=mold
-          make -j"$(nproc)" V=s || make -j1 V=s
-
+          for i in {1..3}; do
+            make -j"$(nproc)" V=s && break || {
+              echo "Build attempt $i failed, retrying..."
+              make clean
+              sleep 30
+            }
+          done
       - name: Optimize Binaries
         run: |
           cd openwrt/bin/targets/${TARGET}/${SUBTARGET}
